# Site settings
title: "FlowAudio - Auto Volume"
description: "Privacy Policy and Terms of Service"

# Build settings
theme: jekyll-theme-cayman # Or jekyll-theme-minima

# Plugins
plugins:
  - jekyll-optional-front-matter
